### ISSUE TITLE
types don't match 

### ISSUE THREAD

**Issue by zakarianamikaz** [HassanAzzam/Arabic-NER#2]
python3 train.py
Using TensorFlow backend.
Loading Word Embedding model...
loaded model in 509.5450041294098 seconds
WARNING:tensorflow:From /home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From /home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3239: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Traceback (most recent call last):
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 471, in _apply_op_helper
    as_ref=input_arg.is_ref)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1293, in internal_convert_n_to_tensor
    ctx=ctx))
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1224, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1018, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype bool for Tensor with dtype float32: 'Tensor("crf_1/zeros_like_4:0", shape=(?, ?), dtype=float32)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 130, in <module>
    train_model, crf_layer = model.build_model()
  File "/home/zakaria/Downloads/Arabic-NER-master (1)/Arabic-NER-master/model.py", line 22, in build_model
    output_layer = crf_layer(bi_gru)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/keras/engine/base_layer.py", line 451, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/keras_contrib-2.0.8-py3.7.egg/keras_contrib/layers/crf.py", line 292, in call
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/keras_contrib-2.0.8-py3.7.egg/keras_contrib/layers/crf.py", line 564, in viterbi_decoding
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/keras_contrib-2.0.8-py3.7.egg/keras_contrib/layers/crf.py", line 516, in recursion
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2176, in concatenate
    return tf.concat([to_dense(x) for x in tensors], axis)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 1299, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1256, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 499, in _apply_op_helper
    raise TypeError("%s that don't all match." % prefix)
TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [bool, float32] that don't all match.

**Comment by zakarianamikaz** [comment]
i made changes : float64 to 32 but not working

**Comment by HassanAzzam** [comment]
I think the problem is related to versions. Check Tensorflow version.
Also, try to use Python 3.6 instead and see what happens.

**Comment by itinawi** [comment]
@HassanAzzam any chance you can push the versions of the packages you were using? A `pip freeze` would be very helpful, as I'm encountering the same problem.

**Comment by itinawi** [comment]
Also, I tried `pip install tensorflow==1.12.0` and it worked. Still having the `pip freeze` output would be helpful!

**Comment by hamadalaqeel** [comment]
For me, it worked by using Python 3.6.6 and installing the following versions :

- `pip install seqeval==0.0.5`
- `pip install keras==2.2.4`
- `git clone https://www.github.com/keras-team/keras-contrib.git
   cd keras-contrib
  python setup.py install`

- `pip install tensorflow==1.14.0`
